### ISSUE TITLE
Heads up, there will be a PR covering some on `[mutex, fiber, io_buffer, fiber_scheduler, threads]` soon ish

### ISSUE THREAD

**Issue by ms-jpq** [matsadler/magnus#11]
I dont want to make it a draft and have a billion notifications for you yet.

**Comment by matsadler** [comment]
Cool, I’ll look forward to seeing it. Thanks for the notice.

Sorry for taking a while to get back to you. I’d been thinking a little myself on how to handle threading, and was going to try and write up some notes, but I just haven’t had time.

**Comment by ms-jpq** [comment]
hey, i havnt been getting as much time to finish this as I had hoped, right now i just want to finish writing the fiberscheduler using tokio before I hand the patch in.

**Comment by jpcamara** [comment]
> hey, i havnt been getting as much time to finish this as I had hoped, right now i just want to finish writing the fiberscheduler using tokio before I hand the patch in.
> 
> 

@ms-jpq curious if you ever got anywhere with your tokio based scheduler?
