### ISSUE TITLE
`try_convert` compiles for `Vec<(T,)>`, but not `Vec<T>`

### ISSUE THREAD

**Issue by ankane** [matsadler/magnus#119]
Hi @matsadler, hope you're doing well.

I ran into some unexpected behavior with `try_convert` (but there may be a reason for it).

```rust
use magnus::{Error, TryConvert, Value};

struct MyType {}

impl TryConvert for MyType {
    fn try_convert(_: Value) -> Result<Self, Error> {
        Ok(MyType {})
    }
}

fn hello(v: Value) {
    // works
    Vec::<(MyType,)>::try_convert(v).unwrap();

    // does not work
    Vec::<MyType>::try_convert(v).unwrap();
}
```

The non-tuple version fails to compile with:

```text
Vec::<MyType>::try_convert(v).unwrap();
               ^^^^^^^^^^^ function or associated item cannot be called on `Vec<MyType>` due to unsatisfied trait bounds
...
note: the trait `TryConvertOwned` must be implemented
```

**Comment by matsadler** [comment]
It's not safe to put Ruby's `Value` type on the heap, so `Vec<T>` only implements `TryConvert` where `T` implements `TryConvertOwned`. And `TryConvertOwned` is just a promise that your type doesn't contain a `Value`.

A `unsafe impl TryConvertOwned for MyType {}` should fix your example (as far as getting `Vec::<MyType>::try_convert(v)` working).

`Vec::<(MyType,)>` should encounter the same error, but [I messed up the type bounds for tuples](https://github.com/matsadler/magnus/blob/65e35e5e85a749c335ddf8baef266a9f3744ba2e/src/try_convert.rs#L241-L243). I'll fix that.

**Comment by ankane** [comment]
`MyType` should be fine to put on the heap, right? (since it shouldn't contain a value?)

**Comment by ankane** [comment]
Ah, I think I see what you're saying. The code should use `unsafe impl TryConvertOwned for MyType {}` if it won't contain a value.

**Comment by matsadler** [comment]
> The code should use `unsafe impl TryConvertOwned for MyType {}` if it won't contain a value.

Yep, that's it. `TryConvertOwned` is just a marker trait that requires `TryConvert` for the actual implementation. Similar to how [`PartialEq`](https://doc.rust-lang.org/stable/std/cmp/trait.PartialEq.html) has the equality implementation, and [`Eq`](https://doc.rust-lang.org/stable/std/cmp/trait.Eq.html) is just a promise on top of that that the type is fully equivalent.

**Comment by ankane** [comment]
Great, thanks @matsadler!
