### ISSUE TITLE
Question: handles async function from Rust

### ISSUE THREAD

**Issue by jychen7** [matsadler/magnus#12]
hi @matsadler , thanks for creating this useful project. I am creating a ruby bindings for a rust crate. There are a few async functions from Rust need to `await`. In pyo3 (python bindings for rust), I find following works, is there an equivalent in Magnus?

https://github.com/datafusion-contrib/datafusion-python/blob/a5b10e8ef19514361fc6062a8ad63d7a793c2111/src/utils.rs#L25-L32
https://github.com/PyO3/pyo3/blob/main/src/marker.rs

**Comment by jychen7** [comment]
looks like tokio Runtime is fine, without ruby GIL
https://github.com/jychen7/datafusion-ruby/blob/299e8b50a50ac899002541d51237f5e028fa4cea/ext/datafusion_ruby/src/utils.rs#L9-L10

**Comment by matsadler** [comment]
Hey, sorry for take a while to get back to you, glad you found a resolution to your issue yourself.

Ruby does have a function to release the GIL, [`rb_thread_call_without_gvl`](https://github.com/ruby/ruby/blob/1c3dc0877a894ecd6340277e5f9039c5e87a4ae8/include/ruby/thread.h#L94-L131), but it is incredibly hard to use correctly, and Magnus does not yet expose it.

I think the route you're taking now, just blocking without releasing the GIL is the best way to start, with releasing the GIL as a possible future optimisation when me or someone figures out a safe way to add `rb_thread_call_without_gvl` to Magnus.

Good luck with your project! It'd be really exciting to be able to use datafusion from Ruby

**Comment by jychen7** [comment]
Thank you for your quick reply
