### ISSUE TITLE
Question: how to use `method!` bind with a mutuable reference and `Ruby`

### ISSUE THREAD

**Issue by erickguan** [matsadler/magnus#123]
This question goes beyond my current understanding of traits, macros, and mutable references in Rust. I will describe the problem I am fixing with a code example. When implementing an I/O class for [OpenDAL](https://github.com/apache/opendal), I am having trouble understanding what Rust's compiler (rustc) is trying to tell me:

```rust
use std::io::Read;
use std::io::Write;

use magnus::class;
use magnus::method;
use magnus::prelude::*;
use magnus::Error;
use magnus::RModule;

use crate::*;

#[magnus::wrap(class = "OpenDAL::IO", free_immediately, size)]
pub struct OpenDALIO {
    reader: Option<ocore::StdReader>,
    writer: Option<ocore::StdWriter>,
    is_reader_open: bool,
    is_writer_open: bool,
}


pub fn format_io_error(err: std::io::Error) -> Error {
    Error::new(exception::standard_error(), err.to_string())
}

impl OpenDALIO {
    fn close_write(&mut self) -> Result<(), Error> {
        if self.is_writer_open {
            self.writer.as_mut().expect("writer is available").close().map_err(format_io_error)?;
            self.is_writer_open = false;
        }

        Ok(())
    }
}


pub fn include(gem_module: &RModule) -> Result<(), Error> {
    let class = gem_module.define_class("IO", class::object())?;
    // ...
    class.define_method("close_write", method!(OpenDALIO::close_write, 0))?;
}
```

rustc gives me the following error message:

```
error[E0599]: the method `call_handle_error` exists for fn item `fn(&mut OpenDALIO) -> Result<(), Error> {OpenDALIO::close_write}`, but its trait bounds were not satisfied
   --> src/opendal_io.rs:485:40
    |
485 |     class.define_method("close_write", method!(OpenDALIO::close_write, 0))?;
    |                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ method cannot be called due to unsatisfied trait bounds
    |
    = note: the following trait bounds were not satisfied:
            `<for<'a> fn(&'a mut OpenDALIO) -> Result<(), magnus::Error> {OpenDALIO::close_write} as FnOnce<(&Ruby, _)>>::Output = _`
            which is required by `for<'a> fn(&'a mut OpenDALIO) -> Result<(), magnus::Error> {OpenDALIO::close_write}: RubyMethod0<_, _>`
            `for<'a> fn(&'a mut OpenDALIO) -> Result<(), magnus::Error> {OpenDALIO::close_write}: Fn<(&Ruby, _)>`
            which is required by `for<'a> fn(&'a mut OpenDALIO) -> Result<(), magnus::Error> {OpenDALIO::close_write}: RubyMethod0<_, _>`
            `<&for<'a> fn(&'a mut OpenDALIO) -> Result<(), magnus::Error> {OpenDALIO::close_write} as FnOnce<(&Ruby, _)>>::Output = _`
            which is required by `&for<'a> fn(&'a mut OpenDALIO) -> Result<(), magnus::Error> {OpenDALIO::close_write}: RubyMethod0<_, _>`
            `&for<'a> fn(&'a mut OpenDALIO) -> Result<(), magnus::Error> {OpenDALIO::close_write}: Fn<(&Ruby, _)>`
            which is required by `&for<'a> fn(&'a mut OpenDALIO) -> Result<(), magnus::Error> {OpenDALIO::close_write}: RubyMethod0<_, _>`
            `&mut for<'a> fn(&'a mut OpenDALIO) -> Result<(), magnus::Error> {OpenDALIO::close_write}: Fn<(_,)>`
            which is required by `&mut for<'a> fn(&'a mut OpenDALIO) -> Result<(), magnus::Error> {OpenDALIO::close_write}: Method0<_, _>`
            `<&mut for<'a> fn(&'a mut OpenDALIO) -> Result<(), magnus::Error> {OpenDALIO::close_write} as FnOnce<(&Ruby, _)>>::Output = _`
            which is required by `&mut for<'a> fn(&'a mut OpenDALIO) -> Result<(), magnus::Error> {OpenDALIO::close_write}: RubyMethod0<_, _>`
            `&mut for<'a> fn(&'a mut OpenDALIO) -> Result<(), magnus::Error> {OpenDALIO::close_write}: Fn<(&Ruby, _)>`
            which is required by `&mut for<'a> fn(&'a mut OpenDALIO) -> Result<(), magnus::Error> {OpenDALIO::close_write}: RubyMethod0<_, _>`
    = note: this error originates in the macro `method` (in Nightly builds, run with -Z macro-backtrace for more info)
```

Regarding mutable references, does this mean magnus does not support mutable references for structs, or is something else causing this issue?

Regarding the `Ruby` struct, can I insert a `Ruby` struct into the method’s stack? I’m interested in obtaining the exception class.
Currently, I'm ussing `Error::new(magnus::exception::standard_error(), format!("OpenDAL doesn't support mode: {mode}"))` but the magnus documentation recommends getting exception classes from a `Ruby` struct.

**Comment by matsadler** [comment]
The [`method!` macro is actually pretty simple](https://github.com/matsadler/magnus/blob/faad1424ae34a477f47d5b5f40b8345776c88026/src/method.rs#L858-L864), but it's backed by some [fairly complex traits](https://github.com/matsadler/magnus/blob/faad1424ae34a477f47d5b5f40b8345776c88026/src/method.rs#L678-L776). Unfortunately errors tend to barf up a lot of those implementation details in an unhelpful way. You're right though, the problem it's trying to communicate to you is that you can't bind a function with a mutable reference.

Magnus can't bind functions with mutable references, as `&mut` implies a unique reference, which is something that's impossible to promise with Ruby's native API. There's an example using [`RefCell`](https://doc.rust-lang.org/stable/std/cell/struct.RefCell.html) to implement interior mutability in [`examples/mut_point.rs`](https://github.com/matsadler/magnus/blob/faad1424ae34a477f47d5b5f40b8345776c88026/examples/mut_point.rs).

To get ahold of a reference to the `Ruby` struct, functions bound with `method!` (or `function!`) can optionally be defined with a first argument of `&Ruby`, like `fn close_write(ruby: &Ruby, &rb_self: Self) -> Result<(), Error>`.

**Comment by erickguan** [comment]
Thanks for your detailed answer, Mat! I understand much more.

> The [method! macro is actually pretty simple](https://github.com/matsadler/magnus/blob/faad1424ae34a477f47d5b5f40b8345776c88026/src/method.rs#L858-L864), but it's backed by some [fairly complex traits](https://github.com/matsadler/magnus/blob/faad1424ae34a477f47d5b5f40b8345776c88026/src/method.rs#L678-L776).

The `method_n` macro is quite impressive to read and powerful.

> Magnus can't bind functions with mutable references, as &mut implies a unique reference, which is something that's impossible to promise with Ruby's native API. There's an example using [RefCell](https://doc.rust-lang.org/stable/std/cell/struct.RefCell.html) to implement interior mutability in [examples/mut_point.rs](https://github.com/matsadler/magnus/blob/faad1424ae34a477f47d5b5f40b8345776c88026/examples/mut_point.rs).

Perfect. I will go with the `RefCell` route.

I know `TypedData_Make_Struct` being the new Ruby API to wrap custom struct, which I had used. Is this the underlying implementation for Magnus? I assume `wrap` macro uses it somehow but I think I didn't get the whole structure mentally...

> To get ahold of a reference to the Ruby struct, functions bound with method! (or function!) can optionally be defined with a first argument of &Ruby, like fn close_write(ruby: &Ruby, &rb_self: Self) -> Result<(), Error>.

Nice, thanks!

-----

Do you want me to organize your answer into some documentations to magnus?

**Comment by matsadler** [comment]
> I know `TypedData_Make_Struct` being the new Ruby API to wrap custom struct, which I had used. Is this the underlying implementation for Magnus? I assume `wrap` macro uses it somehow but I think I didn't get the whole structure mentally...

Magnus uses [`rb_data_typed_object_wrap` to wrap a struct](https://github.com/matsadler/magnus/blob/faad1424ae34a477f47d5b5f40b8345776c88026/src/r_typed_data.rs#L148) as a Ruby object, and [`rb_check_typeddata` to get a pointer to a wrapped stuct](https://github.com/matsadler/magnus/blob/faad1424ae34a477f47d5b5f40b8345776c88026/src/r_typed_data.rs#L393) from a Ruby object, which are part of the same api as `TypedData_Make_Struct`.
Off the top of my head (so I might be remembering slightly wrong) `TypedData_Make_Struct` will allocate memory for the struct and return a pointer to the uninitialised memory for you to write to, which is a pretty nasty API to use from Rust. `rb_data_typed_object_wrap` instead accepts a pointer to a struct you've initialised, so a better fit for Rust.

The [`#[wrap]` macro](https://github.com/matsadler/magnus/blob/faad1424ae34a477f47d5b5f40b8345776c88026/magnus-macros/src/lib.rs#L209) is actually a really small macro that just delegates to derive macros for the `DataTypeFunctions` and `TypedData` traits implement those traits to set up the `data_type` struct that you have to pass to `rb_data_typed_object_wrap`/`rb_check_typeddata`.

> > To get ahold of a reference to the Ruby struct, functions bound with method! (or function!) can optionally be defined with a first argument of &Ruby, like fn close_write(ruby: &Ruby, &rb_self: Self) -> Result<(), Error>.
> 
> Nice!
> 
> Update: I tried to use `ruby` in a class but it seems not working. Can you check [this example with Point](https://github.com/erickguan/test-magnus/blob/master/src/main.rs#L23)? The idea is to use it in the `Impl` block for Point class.

You need to update any use of `self` within the function body to `rb_self`, or whatever you named the `&Self` parameter, e.g
```
fn y(ruby: &Ruby, rb_self: &Self) -> isize {
    let _ = ruby.qtrue();
    rb_self.y
}
```

> Do you want me to organize your answer into some documentations to magnus?

If you would like to contribute to the documentation that'd be really helpful.

**Comment by erickguan** [comment]
> If you would like to contribute to the documentation that'd be really helpful.

Yes, I added a few commits in a PR.

I have a few other questions. I will add a new issue to keep threads clean.
