### ISSUE TITLE
Ease of accepting `TypedData` arguments

### ISSUE THREAD

**Issue by ianks** [matsadler/magnus#15]
So I'm running up against a scenario where I would like to accept some `TypedData` arguments, and experiencing some paint points. Take this example:

```rust
use magnus::{define_class, function, prelude::*, Error};

#[derive(Debug, Clone)]
#[magnus::wrap(class = "Point")]
struct Point {}

#[magnus::wrap(class = "Triangle")]
struct Triangle {
    a: Point,
    b: Point,
    c: Point,
}

impl Triangle {
    fn new(a: Point, b: Point, c: Point) -> Self {
        Self { a, b, c }
    }
}

#[magnus::init]
fn init() -> Result<(), Error> {
    define_class("MultiPoint", Default::default())?
        .define_singleton_method("new", function!(Triangle::new, 3))?;
    Ok(())
}

```

Will lead to this error currently:

```
error[E0599]: the method `call_handle_error` exists for struct `Function3<fn(Point, Point, Point) -> Triangle {Triangle::new}, Point, Point, Point, Triangle>`, but its trait bounds were not satisfied
  --> src/lib.rs:23:41
   |
5  | struct Point {}
   | ------------ doesn't satisfy `Point: TryConvert`
...
23 |         .define_singleton_method("new", function!(Triangle::new, 3))?;
   |                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^ method cannot be called on `Function3<fn(Point, Point, Point) -> Triangle {Triangle::new}, Point, Point, Point, Triangle>` due to unsatisfied trait bounds
   |
   = note: the following trait bounds were not satisfied:
           `Point: TryConvert`
note: the following trait must be implemented
  --> /Users/ianks/.cargo/git/checkouts/magnus-af51bb84edff177b/cc852bf/src/try_convert.rs:17:1
   |
17 | / pub trait TryConvert: Sized {
18 | |     /// Convert `val` into `Self`.
19 | |     fn try_convert(val: Value) -> Result<Self, Error>;
20 | | }
   | |_^
   = note: this error originates in the macro `function` (in Nightly builds, run with -Z macro-backtrace for more info)
```

### The Issue

Currently, [`TryConvert`] is only implemented for `&TypedData`][try-convert]. However, `TypedData` cannot be derived for generic types (i.e. you cannot specify the lifetime of each point in the triangle `struct Triangle<'point>`). So when taking the `&Point` arg by reference, you have to clone the point:

```diff 
 impl Triangle {
-    fn new(a: Point, b: Point, c: Point) -> Self {
-        Self { a, b, c }
+    fn new(a: &Point, b: &Point, c: &Point) -> Self {
+        Self {
+            a: a.clone(),
+            b: b.clone(),
+            c: c.clone(),
+        }
     }
 }
```

### Potential Solutions

Since the `wrap` macro is a bit hidden, it took me a bit to understand what the issue was, and I imagine this will be a pain point for others adopting magnus as well. Here are a couple of ideas I had for fixing it:

1. Add a `impl<T: TypedData> TryConvert for T` which would effective do the cloning for you (easiest for the end user, easier to implement)
2. Add ability to derive when using lifetimes with `TypedData` so users could specify that the `&'point Point` would live at least as long as the triangle (hardest for end user, hardest to implement. Also unsound if the user doesn't mark `Point` correctly...)

Curious to hear your thoughts, maybe there is a better way?

[try-convert]: https://github.com/matsadler/magnus/blob/main/src/r_typed_data.rs#L498

**Comment by matsadler** [comment]
(writing this on my phone, sorry if formatting is terrible)

I screwed up with `impl<T: TypedData> TryConvert for &T` such that you can get any lifetime you want out of it, like `&'static Point` would 'work', so I’m going to make some changes to it. One of those will probably be removing the blanket impl and having the `wrap` macro generate is for you specifically for you type. I could probably  add an option to the macro to generate a cloning impl.

In the meantime will Rust let you `impl TryConvert` yourself? Something like

```rust
impl TryConvert for Point {
    fn try_convert(val: Value) -> Result<Self, Error> {
        val.try_convert::<&Point>().map(|p| p.clone())
    }
}
```

**Comment by ianks** [comment]
I was able to get past it, just figured it was a good opportunity to provide some feedback on the ergonomics.

Thinking about lifetimes / GC a bit more, it would be so nice to have magnus manage them somehow. This is totally off the cuff, but hear me out:

Imagine you store an `RString` in a `TypedData` struct. In order to have any safety guarantees about the lifetime of that `RString`, you need to ensure that it is `gc::mark`’d. So, I wonder if there is a way to encapsulate that in a type (such as `GcMarked<RString>`), and automatically generate the `dmark` method. With that, you could declare a valid dependent lifetime for the `TypedData` struct, which specifies that the `RString` lives *at least as long as `TypedData`. it would be something like:

```rust
struct Thing<`thing, R: GcMarked + `thing>(R);
```

On my phone as well, so that may just be complete gibberish, but hopefully I made some sense. The idea would be to *automatically generate the mark function so we could statically check the lifetimes of ruby objects stored in typed data structs*.

Would be nifty!
