### ISSUE TITLE
Thoughts on this idea for a `WrappedStruct`?

### ISSUE THREAD

**Issue by ianks** [matsadler/magnus#28]
One common pattern we keep running into is the need for one magnus wrapped struct to hold and reference another ([especially in `wasmtime-rb`](https://github.com/search?q=repo%3Abytecodealliance%2Fwasmtime-rb%20DataTypeFunctions&type=code)).

Doing this today is tedious, and not super intuitive for new users. You have to understand how magnus works under the hood to realize the solution -- which is to store a `Value` in your struct on rely on `TryConvert`.

Here's an example on what you have to do to keep a reference on a struct today:

Given we have a point:

```rust
// point.rs

#[magnus::wrap(class = "Point", free_immediatly)]
struct Point(f64, f64);

impl Point {
    fn new(a: f64, b: f64) -> Self {
        Self(a, b)
    }
}
```

### Old

```rust
#[derive(TypedData)]
#[magnus(class = "Line", free_immediatly)]
struct Line(Value, Value);

impl Line {
    fn new(a: Value, b: Value) -> Self {
        Self { a, b }
    }

    fn length(&self) -> Result<f64, Error> {
        let a: &Point = self.a.try_convert()?;
        let b: &Point = self.b.try_convert()?;

        Ok(((a.0 - b.0).powi(2) + (a.1 - b.1).powi(2)).sqrt())
    }
}

impl DataTypeFunctions for Line {
    fn mark(&self) {
        gc::mark(&self.a);
        gc::mark(&self.b);
    }
}

unsafe impl Send for Line {}
```

### New

Given this is such a common pattern, I'm proposing a lightweight solution for it. The main goals for  it are to:

1. Make it clear to anyone that reads the code that you are storing a magnus struct, instead of just  `Value`
2. Keep track of the struct type information so it's easy to use (not have to know to use `try_convert`)
3. Make it as easy as possible to mark for GC, since you'll have a really bad time otherwise

For now, I'm calling this thing `WrappedStruct<T>`, but open to other names... and other improvements in general. Here is how it would look:

```rust
#[derive(TypedData)]
#[magnus(class = "Line", free_immediatly)]
struct Line {
    a: WrappedStruct<Point>, // instead of `Value`
    b: WrappedStruct<Point>
};

impl Line {
    fn new(a: WrappedStruct<Point>, b: WrappedStruct<Point>) -> Self {
        Self(a, b)
    }

    fn length(&self) -> Result<f64, Error> {
        let a = self.a.get()?;
        let b = self.b.get()?;

        Ok((a.0 - b.0).powi(2) + (a.1 - b.1).powi(2)).sqrt())
    }
}

impl DataTypeFunctions for Line {
    fn mark(&self) {
        self.a.mark();
        self.b.mark();
    }
}
```

### Impl

It's just a small generic container for `TypedData` with a thin interface. In case you want to test it out, I [created a gist with an implementation you can just drop into your app](https://gist.github.com/ianks/1f040ffd515e855bc5d36066e43d9bf6).

WDYT?

**Comment by matsadler** [comment]
Sorry for taking ages to get around to responding to this.

Yeah, I agree something like this is needed. I've added a [`typed_data::Obj`](https://github.com/matsadler/magnus/blob/ae792419bed70107d4c930e1f8193272750b9fd2/src/typed_data.rs#L372-L385) that pretty much follows the pattern of your example. I put a [usage example in a test](https://github.com/matsadler/magnus/blob/ae792419bed70107d4c930e1f8193272750b9fd2/tests/typed_data_obj.rs).

The key part is
``` rust
#[derive(TypedData)]
#[magnus(class = "Line", free_immediatly, mark)]
struct Line {
    start: Obj<Point>,
    end: Obj<Point>,
}

impl Line {
    fn new(start: Obj<Point>, end: Obj<Point>) -> Self {
        Self { start, end }
    }

    fn length(&self) -> f64 {
        let start = self.start.get();
        let end = self.end.get();

        (((end.x - start.x).pow(2) + (end.y - start.y).pow(2)) as f64).sqrt()
    }
}

impl DataTypeFunctions for Line {
    fn mark(&self) {
        gc::mark(self.start);
        gc::mark(self.end);
    }
}
```

I went with `typed_data::Obj` as the name as you can either use it like that for a more descriptive longer name, or as `Obj` for something short. Hopefully the name reminds people it's a Ruby object that is subject to the GC and needs marking in cases like the above example.

Let me know if that works out.

**Comment by ianks** [comment]
🔥 Way easier to write than WrappedStruct. Thanks @matsadler

**Comment by uvlad7** [comment]
@matsadler I'm sorry for necroposting, but is this a way to bypass this:

> When using Magnus, in Rust code, Ruby objects must be kept on the stack. If objects are moved to the heap the Ruby GC can not reach them, and they may be garbage collected. This could lead to memory safety issues.

I mean, I thought there is currently no way to `mark` `Value`s, but it actually seems to be possible.

**Comment by matsadler** [comment]
@uvlad7 There's a few APIs for informing Ruby about Values that are not on the stack, see [`gc::register_mark_object`](https://docs.rs/magnus/0.6.2/magnus/gc/fn.register_mark_object.html), [`gc::register_address`](https://docs.rs/magnus/0.6.2/magnus/gc/fn.register_address.html)/[`gc::unregister_address`](https://docs.rs/magnus/0.6.2/magnus/gc/fn.unregister_address.html) (also [`BoxValue`](https://docs.rs/magnus/0.6.2/magnus/value/struct.BoxValue.html) that wraps register/unregister as a type), and the last example for [`TypedData`](https://docs.rs/magnus/0.6.2/magnus/derive.TypedData.html).
