### ISSUE TITLE
`warning: undefining the allocator of T_DATA class` from ruby-head

### ISSUE THREAD

**Issue by AlexanderPavlenko** [matsadler/magnus#43]
Seems identical to https://github.com/robinst/taglib-ruby/issues/115
Just checking out Magnus, thanks for your work!

**Comment by matsadler** [comment]
This was fixed in #41.

I was planning on it going out in the 0.5 release, but I might backport it to 0.4 in the next couple of days.

**Comment by matsadler** [comment]
I've puts out a 0.4.4 release with this fix.
