### ISSUE TITLE
Ruby Inheritance

### ISSUE THREAD

**Issue by ankane** [matsadler/magnus#49]
Hey @matsadler, hope your year is off to a good start.

I was wondering if you've given any thought to how to do Ruby inheritance (recently came across the need for this with [Tokenizers](https://github.com/ankane/tokenizers-ruby)). For instance, in the code below, it'd be nice to be able to have a `Shape` class with `Circle` and `Rectangle` subclasses, and support passing those subclasses to functions that accept `Shape` as an argument.

```rust
enum Shape {
    Circle { r: f32 },
    Rectangle { x: f32, y: f32 },
}

impl Shape {
    pub fn area(&self) -> f32 {
        match self {
            Shape::Circle { r } => std::f32::consts::PI * r * r,
            Shape::Rectangle { x, y } => x * y,
        }
    }
}

fn print_area(s: &Shape) {
    println!("{}", s.area());
}

fn main() {
    let a = Shape::Circle { r: 1.0 };
    let b = Shape::Rectangle { x: 2.0, y: 3.0 };
    print_area(&a);
    print_area(&b);
}
```

Edit: [Tokenizers example](https://github.com/ankane/tokenizers-ruby/blob/a77ddea7e7c0f28b8180aebad7edb0a1b8f90d86/ext/tokenizers/src/pre_tokenizers.rs#L31-L49) if it's helpful (the `new` method on subclasses currently returns the parent class)

**Comment by matsadler** [comment]
> Hey @matsadler, hope your year is off to a good start.

Thanks, I'm doing great 🙂

> I was wondering if you've given any thought to how to do Ruby inheritance.

I had not thought about this whatsoever, but I've just taken a look and it was a pretty small change to put together something I hope will address your use case.

The Ruby C API function `VALUE rb_data_typed_object_wrap(VALUE klass, void *datap, const rb_data_type_t *type);` takes the class as a param on each invocation, so you can set a different class every time you call it.
I didn't replicate this exactly, as it seems prone to making mistakes when usually you'd want to set the same `klass` for the same `rb_data_type_t`.

(The other side of the API, `rb_check_typeddata` doesn't care about the class, and just unwraps based on `rb_data_type_t`.)

I've added a `TypedData::class_for(value: &Self)` function that will be passed the Rust value that's being wrapped and should return the class of the object to wrap it in. Hopefully that way it will allow similar flexibility of setting the class to the C API, without the same manual bookkeeping.
This new function defaults to returning `TypedData::class()`, so everything should stay working as it was by default.

There's an [example in the tests in the commit](https://github.com/matsadler/magnus/commit/4f868e8c3d3b061223fd72380c156085351aee96).

And I hope to be able to hook it up with the macros to work something like:
``` rust
#[magnus::wrap(class = "Shape")]
enum Shape {
    #[magnus(class = "Circle")]
    Circle { r: f32 },
    #[magnus(class = "Rectangle")]
    Rectangle { x: f32, y: f32 },
}
```

Let me know if that works, or if it needs some tweaks.

**Comment by ankane** [comment]
Wow, that was super fast - big thanks!!

It's [working well](https://github.com/ankane/tokenizers-ruby/commit/e39b7808a8bde4b24f0b2e4282a955f94878ab81) (went with `const_get` over `define_class` since the classes are already defined in `#[magnus::init]`). Should the string in `data_type()` include the module (`Tokenizers::PreTokenizer`)?

**Comment by matsadler** [comment]
Cool, I'm glad that works.

Ruby says that string doesn't need to be a valid C or Ruby identifier, but does need to uniquely identify that data type. The easiest thing to do (and what the `wrap` macro does) is use the full class name, with the module.

**Comment by ankane** [comment]
Great, thanks again!
