### ISSUE TITLE
Outdated error examples in readme

### ISSUE THREAD

**Issue by ankane** [matsadler/magnus#53]
Hey @matsadler, it looks like `Error::type_error` and `Error::encoding_error` shown in [this example](https://github.com/matsadler/magnus/tree/3e077d9ea7b35afd705f2c54fafeb9c8c57cf311#manual-conversions) were removed in 0.3.0 (although I personally think it'd be convenient to have them).

**Comment by matsadler** [comment]
Oops. Thanks for catching this. Should be fixed now.

**Comment by ankane** [comment]
Thanks @matsadler!
