### ISSUE TITLE
Embedded Ruby and require_relative

### ISSUE THREAD

**Issue by SlashScreen** [matsadler/magnus#65]
I am attempting to embed ruby as a scripting application for this project. I am magnus::eval<>-ing a file I read to string, and attempting to require one of my files containing a custom class in rust. My file structure looks like this: 
![image](https://user-images.githubusercontent.com/12375239/224404318-cdcb5608-cbf6-496f-b2dc-d029aa75d7fe.png)
and `test.rb` looks like:
```rb
require_relative 'src/core/position'

class Test
  def initialize; end;
  def run
    puts "Hello World!"
  end
end

Test.new.run
puts Position.new(1, 2, 3).to_s
```
But it says it cannot find the file. Am I misunderstanding how to do this? Is magnus the right library to use for this task, or should I use something like rtie or artichoke instead? 
Also, some other questions:
1) How do I magnus::init multiple classes?
2) Would a user of this app need ruby installed on the system? I imagine so, no? Would I have to embed a runtime like artichoke?

**Comment by matsadler** [comment]
I've [added an example](https://github.com/matsadler/magnus/tree/0.5/examples/embed) of a multi-file embedded project, hopefully that helps.

It is possible to statically link Ruby into an application, and Magnus supports this, in which case the user would not need Ruby installed. However Ruby (as in the runtime, MRI/CRuby) isn't really built to be statically linked, lots of functionality of Ruby is written in Ruby, and this doesn't get included.

I believe Rutie would work similarly to Magnus with regards to requiring files, static linking, etc.

[mruby](https://mruby.org) is an alternate implementation of Ruby that is built specifically for embedding. [minutus](https://github.com/genya0407/minutus) is a project to provide Rust bindings to mruby with a similar api to Magnus. I've not used minutus or contributed to it, I just know it exists.

artichoke is another alternate implementation of Ruby that starts with mruby (which is written in C) and replaces parts with Rust. I believe the goal is eventually to replace all the the mruby C code. I have no idea how usable it is embedded in a Rust application.

**Comment by SlashScreen** [comment]
Thank you, this was helpful. What's the proper way to expose variables? `define_attr` seems to be just for building classes programmatically, is it more proper to use methods as a getter and setter?

**Comment by matsadler** [comment]
It's kind of dependant on your use case, here's an example with a few different ways to expose a value to Ruby, hopefully one works for you:

``` rust
use magnus::{
    current_receiver, define_global_const, define_global_function, define_module, define_variable,
    eval, function, prelude::*, Error, RObject,
};

fn examples() -> Result<(), Error> {
    // Set a global variable
    define_variable("example", 1)?;

    let result: bool = eval!("$example == 1")?;
    assert!(result);

    // Set a constant
    define_global_const("EXAMPLE", 2)?;

    let result: bool = eval!("EXAMPLE == 2")?;
    assert!(result);

    // define a global function
    fn example_fn() -> i64 {
        3
    }
    define_global_function("example", function!(example_fn, 0));

    let result: bool = eval!("example == 3")?;
    assert!(result);

    // define a local variable (eval only)
    let example = 4;
    let result: bool = eval!("example == 4", example)?;
    assert!(result);

    // alternative define a local variable (eval only)
    let result: bool = eval!("example == 5", example = 5)?;
    assert!(result);

    // set an instance variable on the current object (the root `main` in this
    // case). The name must be prefixed with @ to be visible to Ruby
    let main: RObject = current_receiver()?;
    main.ivar_set("@example", 6)?;

    let result: bool = eval!("@example == 6")?;
    assert!(result);

    // namespaced constant
    let module = define_module("Example")?;
    module.const_set("VALUE", 7)?;

    let result: bool = eval!("Example::VALUE == 7")?;
    assert!(result);

    // namespaced function
    let module = define_module("Example")?;
    fn value_fn() -> i64 {
        8
    }
    module.define_singleton_method("VALUE", function!(value_fn, 0))?;

    let result: bool = eval!("Example::value == 8")?;
    assert!(result);

    Ok(())
}

fn main() {
    let _cleanup = unsafe { magnus::embed::init() };
    if let Err(e) = examples() {
        eprintln!("{}", e);
        std::process::exit(1);
    }
}
```

**Comment by SlashScreen** [comment]
Ah, I was looking at exposing a struct's fields.

**Comment by matsadler** [comment]
Oh yeah, getters and setters are the way to go there. See [`examples/mut_point.rs`](https://github.com/matsadler/magnus/blob/0.5/examples/mut_point.rs).
