### ISSUE TITLE
Question: raise custom exception

### ISSUE THREAD

**Issue by jonian** [matsadler/magnus#7]
Hi @matsadler, this is a great project! Apologies for using issues to ask a question but discussions are not enabled. My experience with rust is minimal and magnus has helped me a lot to write my extension. What I haven't managed to do is raise a custom error. Can you please provide an example how it can be done? Thank you!

**Comment by matsadler** [comment]
Hey!

I've add a couple of examples to the [`examples/`] dir, one defining [custom exceptions entirely in Rust][rs], and another [defining custom exceptions in Ruby][rb0] and then [using them from Rust][rb1].

[`examples/`]: https://github.com/matsadler/magnus/tree/main/examples
[rs]: https://github.com/matsadler/magnus/blob/main/examples/custom_exception_rust/ext/ahriman/src/lib.rs 
[rb0]: https://github.com/matsadler/magnus/blob/main/examples/custom_exception_ruby/lib/ahriman/error.rb
[rb1]: https://github.com/matsadler/magnus/blob/main/examples/custom_exception_ruby/ext/ahriman/src/lib.rs

The two examples should be totally equivalent from the point of view of someone using the extension, so up to you which you prefer. And there's probably a few other ways of doing it, but these should be a good start.

The example of doing it entirely in Rust is kind of clunky and hard to figure out, I should do something to make it easier.

I'm going to close this for now, but if you have any follow up questions on the same topic, or suggestions of how you'd like to see it work, please feel free to reopen this issue.

Thanks!

**Comment by jonian** [comment]
Thank you for the examples. Except raising custom errors I also learned how define a module/class outside init and how to get a module/class defined in ruby.
