### ISSUE TITLE
serde_magnus discontinued?

### ISSUE THREAD

**Issue by gintama91** [matsadler/magnus#82]
not totally related to magnus but idk any better place to ask about this 
refering to https://github.com/matsadler/magnus/pull/47

i tried searching for forks but can't find any , does anyone know what happened?

**Comment by matsadler** [comment]
I don't know what happened, but I hope the author is doing ok.

I do happen to have a reasonably recent local checkout of the code, which I have pushed to https://github.com/matsadler/serde-magnus, but I don't have any plans to maintain it. If the original author is reading this and you'd prefer I take this down, comment here, or my email address is on my GitHub profile.

If anyone takes up maintenance of that crate, let me know and I can link it from the Magnus readme/docs.

**Comment by jwilm** [comment]
OneSignal is starting to work with serde-magnus, and I wanted to share that we published [an update](https://crates.io/crates/serde_magnus) to crates.io to bring the magnus version up to 0.6.2. The code is currently [under the OneSignal org](https://github.com/OneSignal/serde-magnus).

We are not yet using the code in prod, and I can't make any guarantees that we will maintain it in the long term, but for the time being we are happy to maintain and work with the community to fix issues and accept patches.

**Comment by matsadler** [comment]
Great! I've linked to it from the readme and docs (though I've not done a release, so you won't see the links on crates.io/docs.rs til I do).
