### ISSUE TITLE
Question: Is it possible to call a Rust executable with no overhead?

### ISSUE THREAD

**Issue by alexevanczuk** [matsadler/magnus#87]
Hi there! I recently just finished using Magnus to call my rust function from Ruby. Behaviorally, everything works smoothly. Great job on and thank you for creating and maintaining magnus!

After commenting out 100% of my gem except for what is necessary to get all the piping in place, I noticed that it added .8 seconds of overhead. This CLI application should run in under a second in many contexts, so I'm not able to use this approach.

I am trying to explore ways to do this with less or zero overhead. For example, I was wondering if it’s possible to use magnus to make the gem executable call the rust crate’s executable directly (rather than going through magnus to serialize/deserialize between ruby and rust, and other tasks). Alternatively, if by installing the gem it could just add the rust executable to the user’s path, that’d work too. Not sure what is possible and/or best practice.

Do any folks here have any insights or recommendations?

Thank you!

**Comment by matsadler** [comment]
Magnus aims to be "zero-cost", going by the definition of "zero-cost" meaning you couldn't write a faster version (in Rust) if, instead of using Magnus' abstractions, you wrote it out all by hand.

One caveat to that is Magnus aims to always be 'correct', so with Magnus you always get (for example) protection from Ruby exceptions. You might think you could write code that isn't going to encounter an exception so doesn't need this protection and maybe eek out a little more performance, but you'd be surprised how hard it is to prove some Ruby code will 100% never raise an exception.

[rb-sys] is what you'd want to use to get as low level as possible and do everything by hand.

[rb-sys]: https://github.com/oxidize-rb/rb-sys

But here's a quick test (using my [halton](https://github.com/matsadler/halton-rb) gem):

`pure_ruby.rb`
``` ruby
# frozen_string_literal: true

module Halton
  def self.number(base, index)
    factor = 1.0
    result = 0.0
    while index > 0
      factor /= base
      result += factor * (index % base)
      index /= base
    end
    result
  end
end

puts Halton.number(2, 1024)
```

`rust_ext_gem.rb`
``` ruby
# frozen_string_literal: true

# gem install halton
require "halton"

puts Halton.number(2, 1024)
```

``` sh
~> time ruby pure_ruby.rb
0.00048828125

________________________________________________________
Executed in   88.33 millis    fish           external
   usr time   31.85 millis   58.00 micros   31.79 millis
   sys time   20.40 millis  850.00 micros   19.55 millis

~> time ruby rust_ext_gem.rb
0.00048828125

________________________________________________________
Executed in   90.46 millis    fish           external
   usr time   33.47 millis   68.00 micros   33.40 millis
   sys time   21.58 millis  882.00 micros   20.70 millis

```

The extra 2 milliseconds for the Rust version is likely the `require` overhead rather than anything Rust specific.

Maybe I'm misunderstanding but that seems to be very different performance to what you're describing.

Would it be possible for you to create some example code that you could share that shows the issue you're having?

**Comment by alexevanczuk** [comment]
Thanks for the detailed response @matsadler ! Really appreciate it.

I think what I'm realizing is that it seems like 100% of the overhead is coming from (A) my gem's implementation and its dependencies and (B) loading bundler and have it provide the right executable, not Magnus.

I guess I was wondering if you had any recommendations for avoiding this overhead. I'm not sure if there's really a way here since the gem is used in a bundled context and you need to use bundler to load the gem, but it would be awesome if the Rust binary could be installed to the user's path (same way as it's installed with `cargo install`) when the user has the gem installed via bundler.

Do you know how I might accomplish this or to otherwise be able to reduce this (non-magnus) overhead?

Thank you!

**Comment by matsadler** [comment]
When you have a gem with an executable and you install it, RubyGems installs all your gem's files including the executable into directory named something like `yourgem-0.1.0` under `$GEM_HOME`. It then creates a stub executable (written in Ruby) that it places in your path.

This stub executable will load rubygems, activate the chosen version of your gem (did you know you can choose the version of a gem executable by passing the version as first argument surrounded by `_`, like  `somegem _0.1.0_ rest of args`) and then call `load` (which is a slightly lower level version of `require`) with the path to your executable.

If you install a gem via bundler then it's basically the same, but the stub executable is generated by bundler a looks a little different (and won't let you choose a version), but it ends the same way, calling `load` with the path to your executable.

This means your gem's executable must be something that is loadable by Ruby, usually a text file of Ruby code. However, I can't think of any reason it couldn't be the `.so` (or `.bundle`) of a gem extension, although I haven't tried this to know if it'd work.

This would basically mean setting your gemspec to point the executable towards the `.so` file, and then treating the function marked with `#[magnus::init]` as your `main` function.

I don't know if it would win you much time, but it's about the only thing I can think of that you control, as the rest of the process is in the hands of rubygems/bundler.

One fairly major downside is it would make it a lot harder to distribute a pre-compiled version of your gem. While RubyGems supports different `.gem` files for different platforms, it doesn't distinguish between Ruby versions. Extensions can only be compiled for one version of Ruby at a time, so the usual workaround is to precompile for all the Ruby versions you support, and then have the main file users `require` be a stub written in Ruby that detects the version and loads the right extension. But that's the kind of thing you're trying to avoid.

If you can't distribute a pre-compiled gem, then that means users will need to have Rust installed, and then it seems like you could just get them to use `cargo install`.

---

The only other thing I can think of is to include a Rust binary (that is potentially just pure Rust and doesn't even use Magnus) as a file in your gem, then first time your gem executable is run move the Rust binary into the users path then `exec` that path. This'd mean the first time you run it it'd be slow, but after that users would be running the Rust binary directly. There are a bunch of issues with this, you might end up trying to move the binary to a path without write permissions, it would break the isolations of versions provided by bundler, it's not what the user expects, etc.

**Comment by alexevanczuk** [comment]
Thanks so much for all of this helpful info, including all of the educational background – really appreciate it!

I agree with your sentiment that since users will have to have Rust installed, perhaps they should just `cargo install` the Rust CLI crate. For now, it feels like an OK trade-off to have a little performance delay in exchange for simpler installation, and if a user wants, they can make a different tradeoff and install the Rust crate directly.

I'm not sure if long-term it'd make sense for Bundler to make it easy to have a gem's executables be a binary executable written in Rust, but it'd certainly make this problem a bit simpler. I think I'll stray away from unexplored territory for now.

Thanks so much again for your help here as well as building and maintaining Magnus!
