### ISSUE TITLE
MSRV Change

### ISSUE THREAD

**Issue by ryantaylor** [matsadler/magnus#93]
I've been getting CI failures when building my magnus-dependent library on Rust 1.61. It looks like the `regex` crate bumped their MSRV to 1.65 (https://github.com/rust-lang/regex/commit/8e13494bc898db42c64ef6a750203b1e6ce47214). Since `regex` is a dependency of `rb-sys`, building magnus on Rust 1.61 seems to fail now.

**Comment by matsadler** [comment]
Magnus doesn't use any features from after Rust 1.61, and while the way the dependency versions are specified allow for using newer versions of those dependencies, those newer versions are not required. You can set a requirement on the version of the regex crate pinning to an older version to get things building on Rust 1.61 like so:

``` toml
[dependencies]
magnus = "0.6"
regex = "= 1.9.6"
```

I can only really promise the Minimum Supported Rust Version is valid with the versions of the dependencies at the time of release for a specific version of Magnus. You should always be able to check those by looking at the `Cargo.lock` at the tag of the release, e.g. https://github.com/matsadler/magnus/blob/0.6.2/Cargo.lock
This is guaranteed as the tests on CI will aways be run against the MSRV (as well as the latest version of Rust), with the version of the dependencies in the `Cargo.lock` (I also run the tests against the MSRV when developing locally, but that's slightly less of a guarantee as sometimes I forget).
