### ISSUE TITLE
Automatic `frozen?` check

### ISSUE THREAD

**Issue by uvlad7** [matsadler/magnus#97]
Not sure if it's possible to implement, but it would be a nice feature to automatically perform `check_frozen` inside `method` when wrapped function takes `mut rb_self`.

**Comment by matsadler** [comment]
I agree this would be a nice feature to be able to offer with Magnus, but I'm not sure how to achieve it.

Type wise, there isn't any difference between `fn example(mut rb_self: Value)` and `fn example(rb_self: Value)`, the `mut` only concerns the variable binding `rb_self`, it doesn't say anything about the value bound to it. It's not exactly the same (I think there's a potential difference in drop order), but you can think of `fn example(mut rb_self: Value)` being equivalent to:

``` rust
fn example(rb_self: Value) {
    let mut rb_self = rb_self;
    // ...
}
```

Which I think is a good way of highlighting that the `mut` isn't saying anything about the function or its arguments, it's just an internal implementation detail of the function.

If you meant `fn example(rb_self: &mut Something)`, then Magnus doesn't bind functions with mutable references, as `&mut` implies a unique reference, which is something that's impossible to promise with Ruby's native API.

Probably the nicest way I can think of doing this would be an attribute macro, something like:

``` rust
#[frozen_check]
fn example(rb_self: Value) -> Result<(), Error> {
    // ...
}
```

and I don't think that's significantly better than:

``` rust
fn example(rb_self: Value) -> Result<(), Error> {
    rb_self.check_frozen()?;
    // ...
}
```

**Comment by uvlad7** [comment]
Agree, attribute macro doesn't seem to worth the efforts.
