### ISSUE TITLE
Exposing mutable wrapped class methods

### ISSUE THREAD

**Issue by Zapotek** [matsadler/magnus#98]
Hello,

In the [Point](https://github.com/matsadler/magnus#wrapping-rust-types-in-ruby-objects) example, how would one continue to expose the `set_x` method to Ruby?

Cheers!

**Comment by matsadler** [comment]
There's a [full example in the `examples/` directory](https://github.com/matsadler/magnus/blob/663e70029fd493ee2548b333760d7cd57b1b9637/examples/mut_point.rs#L44), it'd look like:

``` rust
class.define_method("x=", method!(MutPoint::set_x, 1))?;
```
then from Ruby you'd use it like:

``` ruby
point = Point.new(1, 2)
point.x    #=> 1
point.x = 3
point.x    #=> 3
```
